# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circonscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_circo', models.TextField()),
                ('num_department', models.TextField()),
                ('department', models.TextField()),
                ('region', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('slug', models.TextField()),
                ('sex', models.TextField()),
                ('mail', models.TextField()),
                ('birth_date', models.DateField()),
                ('birth_town', models.TextField()),
                ('birth_department', models.TextField()),
                ('birth_country', models.TextField()),
                ('work_name', models.TextField()),
                ('work_category', models.TextField()),
                ('work_familly', models.TextField()),
            ],
            options={
                'db_table': 'Deputy',
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.TextField(unique=True)),
                ('start_date', models.TextField()),
                ('seat_number', models.TextField()),
                ('election_cause', models.TextField()),
                ('legislature', models.TextField()),
                ('circonscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_assembly.Circonscription')),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='open_assembly.Deputy')),
            ],
        ),
    ]
