# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circonscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_circo', models.TextField()),
                ('num_department', models.TextField()),
                ('department', models.TextField()),
                ('region', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('slug', models.TextField()),
                ('sex', models.TextField()),
                ('mail', models.TextField()),
                ('birth_date', models.DateField()),
                ('birth_town', models.TextField()),
                ('birth_department', models.TextField(blank=True, null=True)),
                ('birth_country', models.TextField(blank=True, null=True)),
                ('work_name', models.TextField(blank=True, null=True)),
                ('work_category', models.TextField(blank=True, null=True)),
                ('work_familly', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('seat_number', models.TextField()),
                ('election_cause', models.TextField()),
                ('legislature', models.TextField()),
                ('circonscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='open_assembly.Circonscription')),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='open_assembly.Deputy')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('asked_by', models.TextField()),
                ('poll_date', models.DateField()),
                ('session_ref', models.TextField()),
                ('sceance_ref', models.TextField()),
                ('is_accepted', models.BooleanField()),
                ('legislature', models.TextField()),
                ('number_people_voting', models.IntegerField()),
                ('number_votes_made', models.IntegerField()),
                ('number_votes_required', models.IntegerField()),
                ('number_votes_no', models.IntegerField()),
                ('number_votes_yes', models.IntegerField()),
                ('number_votes_dk', models.IntegerField()),
                ('number_votes_not_voting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.IntegerField()),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='open_assembly.Deputy')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='open_assembly.Mandate')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='open_assembly.Poll')),
            ],
        ),
        migrations.AddField(
            model_name='deputy',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deputies', to='open_assembly.Group'),
        ),
    ]
