# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_assembly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='deputy',
        ),
        migrations.AddField(
            model_name='deputy',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='open_assembly.Deputy'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='deputies',
            field=models.ManyToManyField(related_name='mandates', to='open_assembly.Deputy'),
        ),
        migrations.AlterField(
            model_name='deputy',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deputy',
            name='birth_town',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deputy',
            name='mail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deputy',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deputy',
            name='sex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deputy',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deputy',
            name='surname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='circonscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='open_assembly.Circonscription'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='election_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='legislature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='seat_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='asked_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
