# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_assembly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deputy',
            table=None,
        ),
    ]
