# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_assembly', '0002_auto_20160227_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_solemn',
            field=models.BooleanField(default=False),
        ),
    ]
