# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_assembly', '0002_auto_20160221_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='circonscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='open_assembly.Circonscription'),
        ),
    ]
