# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_assembly', '0004_remove_vote_deputy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputy',
            name='sex',
            field=models.NullBooleanField(),
        ),
    ]
